# Generated by Django 4.2.4 on 2023-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/image/', verbose_name='Картинка рецепта'),
            preserve_default=False,
        ),
    ]
