# Generated by Django 4.2.4 on 2023-08-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название рецепта'),
        ),
    ]
